[[TrussC_prebuilt_jll]]
git-tree-sha1 = "bcb281f93beceb48677ef318d92042d8682b3667"
os = "macos"
arch = "aarch64"

    [[TrussC_prebuilt_jll.download]]
    sha256 = "5482d510007c919eadd323226c5c79264494fa2bf1952821ded15ebd4f0b5881"
    url = "https://github.com/funatsufumiya/TrussC_prebuilt_jll_packager.jl/releases/download/v0.2.10/macos-aarch64.tar.gz"

[[TrussC_prebuilt_jll]]
git-tree-sha1 = "bbfe99c44e3ca7d296b843a09b6d179d22ea3432"
os = "linux"
arch = "x86_64"

    [[TrussC_prebuilt_jll.download]]
    sha256 = "55455d739393c64beb4cb40a4d6600e91da1b221f5a0e1bf5ca6782dfa5f3b9a"
    url = "https://github.com/funatsufumiya/TrussC_prebuilt_jll_packager.jl/releases/download/v0.2.10/linux-x86_64.tar.gz"

[[TrussC_prebuilt_jll]]
git-tree-sha1 = "8e0230ca840a37d7b5e64c3ec1c024c7edc6e5a8"
os = "windows"
arch = "x86_64"

    [[TrussC_prebuilt_jll.download]]
    sha256 = "32a331fdb8501009eb8099dcc7d0c581821897fa5b2f72c52baafb8b5c283d62"
    url = "https://github.com/funatsufumiya/TrussC_prebuilt_jll_packager.jl/releases/download/v0.2.10/windows-x86_64.tar.gz"