[[TrussC_prebuilt_jll]]
git-tree-sha1 = "4f94b5f4c933b3312d505694831ef9c265ce3cb6"
os = "macos"
arch = "aarch64"

    [[TrussC_prebuilt_jll.download]]
    sha256 = "671b72194b480a0a0236321bc7c32f12bb591868064e680ca090de403a301247"
    url = "https://github.com/funatsufumiya/TrussC_prebuilt_jll_packager.jl/releases/download/v0.1.1/macos-aarch64.tar.gz"

[[TrussC_prebuilt_jll]]
git-tree-sha1 = "89db8bf66831bb950bfacf2200b8d4a3e0877f5d"
os = "linux"
arch = "x86_64"

    [[TrussC_prebuilt_jll.download]]
    sha256 = "f9ded6b7ba49b469db2fca32cd453cd61273cdf0abe988ab8fc7a2d2ef79dec1"
    url = "https://github.com/funatsufumiya/TrussC_prebuilt_jll_packager.jl/releases/download/v0.1.1/linux-x86_64.tar.gz"

[[TrussC_prebuilt_jll]]
git-tree-sha1 = "0590162f356b02080ad957d4043641b543ebc3ad"
os = "windows"
arch = "x86_64"

    [[TrussC_prebuilt_jll.download]]
    sha256 = "ecddaa0328424012da577e41fb7ebbc40ddaf76d022ee899e31e49c609412578"
    url = "https://github.com/funatsufumiya/TrussC_prebuilt_jll_packager.jl/releases/download/v0.1.1/windows-x86_64.tar.gz"