# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.6"
manifest_format = "2.0"
project_hash = "8b6993d80ada0301b4ece09ca24be890752f484f"

[[deps.Artifacts]]
uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
version = "1.11.0"

[[deps.TrussC_prebuilt_jll]]
deps = ["Artifacts"]
path = "."
uuid = "cfe08a50-4fff-11f1-bfed-990c59676b1f"
version = "0.2.8"
